name: sync acl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  acls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch version-cache.json
        uses: actions/cache@v4
        with:
          path: ./version-cache.json
          key: version-cache.json-${{ github.run_id }}
          restore-keys: |
            version-cache.json-
      
      - name: Show policy
        run: |
          { echo '```json'; cat policy.hujson; echo '```'; } > ${{ runner.tool_cache }}/policy.md
          echo "### Tailscale Policy" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ${{ runner.tool_cache }}/policy.md)" >> $GITHUB_STEP_SUMMARY
      
      - name: Deploy ACL
        if: github.event_name == 'push'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1.3.1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          policy-file: policy.hujson
          action: apply

      - name: Test ACL
        if: github.event_name == 'pull_request'
        id: test-acl
        uses: tailscale/gitops-acl-action@v1.3.1
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
          policy-file: policy.hujson
          action: test
